// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IconFaSolidCarrot: typeof import('~icons/fa-solid/carrot')['default']
    IconFaSolidCheck: typeof import('~icons/fa-solid/check')['default']
    IconIonAdd: typeof import('~icons/ion/add')['default']
    IconIonArrowDown: typeof import('~icons/ion/arrow-down')['default']
    IconIonArrowUp: typeof import('~icons/ion/arrow-up')['default']
    IconIonBackspace: typeof import('~icons/ion/backspace')['default']
    IconIonCaretBack: typeof import('~icons/ion/caret-back')['default']
    IconIonCaretForward: typeof import('~icons/ion/caret-forward')['default']
    IconIonCheckmarkDone: typeof import('~icons/ion/checkmark-done')['default']
    IconIonClose: typeof import('~icons/ion/close')['default']
    IconIonFilter: typeof import('~icons/ion/filter')['default']
    IconIonLogoGithub: typeof import('~icons/ion/logo-github')['default']
    IconIonMenu: typeof import('~icons/ion/menu')['default']
    IconIonNewspaper: typeof import('~icons/ion/newspaper')['default']
    IconIonPencil: typeof import('~icons/ion/pencil')['default']
    IconIonReturnDownBack: typeof import('~icons/ion/return-down-back')['default']
    IconIonSearch: typeof import('~icons/ion/search')['default']
    IconIonSettings: typeof import('~icons/ion/settings')['default']
    IconMdiDatabaseImport: typeof import('~icons/mdi/database-import')['default']
    IconMdiDownload: typeof import('~icons/mdi/download')['default']
  }
}

export { }
