// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IconIonAdd: typeof import('virtual:vite-icons/ion/add')['default']
    IconIonBackspace: typeof import('virtual:vite-icons/ion/backspace')['default']
    IconIonCaretBack: typeof import('virtual:vite-icons/ion/caret-back')['default']
    IconIonCaretDown: typeof import('virtual:vite-icons/ion/caret-down')['default']
    IconIonCaretForward: typeof import('virtual:vite-icons/ion/caret-forward')['default']
    IconIonCaretUp: typeof import('virtual:vite-icons/ion/caret-up')['default']
    IconIonCheckmark: typeof import('virtual:vite-icons/ion/checkmark')['default']
    IconIonClose: typeof import('virtual:vite-icons/ion/close')['default']
    IconIonFilter: typeof import('virtual:vite-icons/ion/filter')['default']
    IconIonLogoGithub: typeof import('virtual:vite-icons/ion/logo-github')['default']
    IconIonMenu: typeof import('virtual:vite-icons/ion/menu')['default']
    IconIonReturnDownBack: typeof import('virtual:vite-icons/ion/return-down-back')['default']
    IconIonSearch: typeof import('virtual:vite-icons/ion/search')['default']
    IconIonSettings: typeof import('virtual:vite-icons/ion/settings')['default']
  }
}

export { }
