// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IconFaSolidCarrot: typeof import('virtual:vite-icons/fa-solid/carrot')['default']
    IconFaSolidCheck: typeof import('virtual:vite-icons/fa-solid/check')['default']
    IconIonAdd: typeof import('virtual:vite-icons/ion/add')['default']
    IconIonArrowDown: typeof import('virtual:vite-icons/ion/arrow-down')['default']
    IconIonArrowUp: typeof import('virtual:vite-icons/ion/arrow-up')['default']
    IconIonBackspace: typeof import('virtual:vite-icons/ion/backspace')['default']
    IconIonCaretBack: typeof import('virtual:vite-icons/ion/caret-back')['default']
    IconIonCaretForward: typeof import('virtual:vite-icons/ion/caret-forward')['default']
    IconIonCheckmarkDone: typeof import('virtual:vite-icons/ion/checkmark-done')['default']
    IconIonClose: typeof import('virtual:vite-icons/ion/close')['default']
    IconIonFilter: typeof import('virtual:vite-icons/ion/filter')['default']
    IconIonLogoGithub: typeof import('virtual:vite-icons/ion/logo-github')['default']
    IconIonMenu: typeof import('virtual:vite-icons/ion/menu')['default']
    IconIonNewspaper: typeof import('virtual:vite-icons/ion/newspaper')['default']
    IconIonPencil: typeof import('virtual:vite-icons/ion/pencil')['default']
    IconIonReturnDownBack: typeof import('virtual:vite-icons/ion/return-down-back')['default']
    IconIonSearch: typeof import('virtual:vite-icons/ion/search')['default']
    IconIonSettings: typeof import('virtual:vite-icons/ion/settings')['default']
    IconMdiDatabaseImport: typeof import('virtual:vite-icons/mdi/database-import')['default']
    IconMdiDownload: typeof import('virtual:vite-icons/mdi/download')['default']
  }
}

export { }
